### PR TITLE
Added message verification endpoint.

### PR DESCRIPTION
**Pull request by braydonf**
Closes https://github.com/bitpay/insight/issues/661
Also needs: https://github.com/bitpay/insight/pull/666

### CODE REVIEW

**Comment by pnagurny** [comment]
This works for me with POST. However with GET I'm not able to get the signature to work. It says it's not 32 bytes. I'm passing it in as a URL param in Postman and I would think it would encode it properly. Are you able to get GET requests to work?

**Comment by braydonf** [comment]
I have only tried via the insight-ui, which I believe is post. I'll check.

**Comment by braydonf** [comment]
The base64 encoded signature needs to be url encoded for the GET requests to work.

**Comment by pnagurny** [comment]
Verified that it works with url encoded signature.

**Pull request merged**
